name: Delete and upload lens

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  delete-and-upload-lens:
    uses: Gravitate-Health/reusable-workflows/.github/workflows/lenses-delete-and-upload.yaml@main
    with:
      tag: "v0.6.0"
