name: Upload lens

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  upload-lens:
    uses: Gravitate-Health/reusable-workflows/.github/workflows/lenses-upload.yaml@main
    with:
      tag: "v0.6.0"
